# Generated by Django 4.2.3 on 2023-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
